<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER Level
    

.PARAMETER Path
    

#>
function New-FSPathObject
{
    param(    
        [Parameter(Mandatory = $true)]
        [ValidateSet('Folder')]
        [string]
        $Level,
    
        [Parameter(Mandatory = $true)]
        [string]
        $Path
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.FLYMigration.v001.Models.FSPath

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
