<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

#
# Module manifest for module 'FLYMigration'
#
# Generated by: Administrator
#
# Generated on: 1/16/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'FLYMigration.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'e18dfd57-31bf-4c45-8d47-0550962b2bf4'

# Author of this module
Author = 'Administrator'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2025 Administrator. All rights reserved.'

# Description of the functionality provided by this module
Description = '<div><p>FLY API provides programmatic access to trigger and manage migration jobs through Web API endpoints. To call FLY API, you must get the API key from FLY interface > Management > General Settings > <a target=''_blank'' href=''/#!/settings/general-settings/apikeys'' rel=''noopener noreferrer'' class=''link''>API Keys</a>. For every Web API call, the API key must be attached to the Authorization header in the HTTP request.</p></div>
                                 <div class=''dxp-docFrame''>Authorization: api_key Mgo8CM3TLB0Kgxdqp9RwKTjBt/p ... E/dBN0Q1/vjzjx0qftB/jc</div> <div><p>In this page, you can try and test the API endpoints by copying and pasting the API key to the api_key text box above.</p></div>
                                 <div><p>Refer to <a target=''_blank'' href=''https://github.com/AvePoint/FLY-Migration/tree/master/WebAPI'' rel=''noopener noreferrer''>Sample Codes</a> for more sample codes.</p></div>
                                 <div><p>If you would like to write PowerShell scripts, please refer to <a target=''_blank'' href=''https://github.com/AvePoint/FLY-Migration/tree/master/PowerShell'' rel=''noopener noreferrer'' class=''link''>PowerShell</a> for more details.</p></div>'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 
               '.\Generated.PowerShell.Commands\FormatFiles\AccountSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\AppProfileModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BasicCredential.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BoxAdvancedSettings.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BoxConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BoxJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BoxMappingContent.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BoxMigrationSharePointObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BoxObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BoxPlanMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BoxPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\BoxPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ChannelMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ConversationsMigrationSettings.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\Credential.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DatabaseModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DatabaseSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DbServiceAccount.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DistributionGroupDestinationMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DistributionGroupSourceMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DropBoxAdvancedSettings.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DropboxConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DropboxJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DropboxMappingContent.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DropboxMigrationSharePointObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DropboxObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DropboxPlanMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DropboxPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\DropBoxPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ErrorModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeConnectionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeDistributionGroupMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeDistributionGroupPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeMailboxModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeMappingContentModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeOnlineConnectionOption.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeOnPremisesConnectionOption.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangePlanExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangePlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangePreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangePreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeServerOption.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ExchangeServiceProviderModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\EXJobSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FileSystemAdvanced.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FileSystemPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FSConnectionsSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FSJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FSMappingContent.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FSMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FSMigrationSharePointObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FSPath.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FSPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\FSPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GmailConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GmailJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GmailMappingContentModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GmailMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GmailMigrationExchangeMailboxModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GmailPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GmailPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GmailPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleChatConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleChatJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleChatMappingContentModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleChatMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleChatPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleChatPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleChatPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleDriveAdvancedSettings.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleDriveConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleDriveJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleDriveMappingContent.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleDriveMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleDriveMigrationSharePointObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleDriveObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleDrivePlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleDrivePreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleGroupMappingContentModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleGroupMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleGroupMigrationExchangeMailboxModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GoogleGroupPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GroupsPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\GroupsPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ImapMigrationExchangeMailboxModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\IMAPPOP3ConnectionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\IMAPPOP3JobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\IMAPPOP3MailBoxObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\IMAPPOP3MappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\IMAPPOP3PlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MappingDetailModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MappingJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\Mappings.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MappingSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsChatConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsChatJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsChatMappingContentModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsChatMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsChatPlanExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsChatPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsPlanExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MSTeamsPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\MultigeoTenantModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\Office365GroupConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\Office365GroupJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\Office365GroupMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\Office365GroupModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\Office365GroupPlanExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\Office365GroupPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDriveConnectionCollectionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDriveConnectionOnlineModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDriveConnectionSummary.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDriveJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDriveJobSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDriveMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDriveObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDrivePlanExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDrivePlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDrivePreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDrivePreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\OneDriveUpdateModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PageResultViewModelListEXJobSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PageResultViewModelListOneDriveJobSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PageResultViewModelListPlanDetailsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PageResultViewModelListSPJobSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PageResultViewModelListSPPlanSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PFPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PFPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PlanDetailsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PlanExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PlanGroupDetailsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PlanGroupExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PlanGroupModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PlanGroupSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PlanNameLabel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PlanSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PolicySummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PostMigrationOptions.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PSTFileConnectionOption.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PSTFileJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PSTFileMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PSTFileModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PSTFilePlanSettingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PstPlanExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PublicFolderConnectionOption.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PublicFolderJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PublicFolderModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PublicFolderPlanExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\PublicFoldersSettings.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ScheduleDetailsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ScheduleModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\ServiceResponseString.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointConnectionCollectionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointConnectionOnlineModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointConnectionOnPremisesModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointConnectionSiteModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointConnectionSummary.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointMappingContent.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointPlanExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SharePointUpdateModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SimpleSchedule.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackCompleteModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackDirectConnectionSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackDirectJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackDirectMappingContentModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackDirectMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackDirectPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackDirectPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackDirectPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackJobExecutionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackMappingContentModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackMappingModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackMigrationMSTeamsObject.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SlackPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SPJobSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\SPPlanSummaryModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\StatusResultModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\TeamsChatPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\TeamsChatPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\TeamsCompleteModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\TeamsPreMapping.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\TeamsPreMigrationModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateBoxPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateDistributionGroupPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateDropBoxPlan.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateExchangePlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateFSPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateGmailPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateGoogleChatPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateGoogleDrivePlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateGoogleGroupPlanSettingsModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateIMAPPOP3PlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateMappingOptions.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateMSTeamsChatPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateMSTeamsPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateOffice365GroupPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateOneDriveConnectionCollectionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdatePSTFilePlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdatePublicFoldersPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateSharePointConnectionCollectionModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateSlackDirectPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UpdateSlackPlanModel.ps1xml', 
               '.\Generated.PowerShell.Commands\FormatFiles\UserMappingsModel.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('PSSwaggerUtility')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Start-GoogleDriveJobByPlan', 'Add-ExchangeDistributionGroupPlan', 
               'Get-PublicFolder', 'Get-GoogleChatConnection', 'Update-SPPlan', 
               'Add-IMAPPOP3Plan', 'Add-FileSystemPreMigration', 'Stop-PSTFileJob', 
               'Find-PSTFileJobsByPlan', 'Get-PublicFolderConnection', 
               'Remove-SlackPlan', 'Add-MicrosoftTeamsChatPlan', 
               'Get-GoogleDriveJob', 'Update-ExchangeDistributionGroupPlan', 
               'Stop-IMAPPOP3Job', 'Get-BoxConnection', 'Start-GoogleChatJobByPlan', 
               'Add-GoogleDrivePlan', 'Remove-SPJob', 'Get-ExchangeServiceProvider', 
               'Get-GoogleChatJob', 'Get-SlackDirectJob', 'Update-OneDrivePlan', 
               'Add-Office365GroupPreMigration', 'Start-PublicFolderJobByPlan', 
               'Get-DropboxPlan', 'Start-PSTFileJobByPlan', 'Add-SlackPreMigration', 
               'Get-SlackDirectConnection', 'Get-GoogleChatPlan', 
               'Stop-Office365GroupJob', 'Update-GoogleDrivePlan', 
               'Get-MicrosoftTeamsPlan', 'Get-DropboxConnection', 
               'Remove-MicrosoftTeamsPlan', 'Find-SlackDirectJobsByPlan', 
               'Get-SlackDirectPolicy', 'Get-PSTFilePlan', 'Remove-PSTFilePlan', 
               'Find-PublicFolderJobsByPlan', 'Find-ExchangeJobsByPlan', 
               'Start-GmailJobByPlan', 'Remove-GoogleChatPlan', 
               'Start-SlackJobByPlan', 'Complete-MicrosoftTeamsPlan', 
               'Remove-GoogleDriveJob', 'Stop-GoogleChatJob', 'Get-ExchangePlan', 
               'Remove-SlackJob', 'Restart-PSTFileJob', 'Add-Database', 
               'Get-Office365GroupPolicy', 'Find-MicrosoftTeamsChatJobsByPlan', 
               'Start-FSJobByPlan', 'Remove-ExchangePlan', 'Get-PublicFolderPolicy', 
               'Start-SPJobByPlan', 'Get-MicrosoftTeamsPolicy', 
               'Add-SharePointPreMigration', 'Find-GoogleChatJobsByPlan', 
               'Stop-OneDriveJob', 'Find-DropboxJobsByPlan', 
               'Remove-MicrosoftTeamsJob', 'Get-Office365GroupPlan', 'Stop-SPJob', 
               'Start-SlackDirectJobByPlan', 'Find-SPJobsByPlan', 
               'Get-PSTFilePolicy', 'Update-PublicFolderPlan', 
               'Start-DropboxJobByPlan', 'Restart-FSJob', 
               'Update-OneDriveConnection', 'Get-IMAPPOP3Jobs', 'Remove-OneDriveJob', 
               'Add-SlackDirectMessagePreMigration', 'Start-OneDriveJobByPlan', 
               'Get-Account', 'Get-BoxJob', 'Find-Office365GroupJobsByPlan', 
               'Get-DropboxPolicy', 'Update-GmailPlan', 'Remove-GmailJob', 
               'Remove-GoogleChatJob', 'Get-SlackConnection', 'Stop-DropboxJob', 
               'Find-BoxJobsByPlan', 'Get-GoogleDriveConnection', 
               'Restart-MicrosoftTeamsChatJob', 'Stop-FSJob', 'Add-GoogleGroupPlan', 
               'Remove-Office365GroupJob', 'Get-FSPolicy', 
               'Update-MappingActionForExchange', 'Restart-GoogleChatJob', 
               'Start-ExchangeJobByPlan', 'Restart-BoxJob', 'Remove-SlackDirectPlan', 
               'Get-DropboxJob', 'Remove-GoogleDrivePlan', 'Start-IMAPPOP3JobByPlan', 
               'Add-SlackDirectPlan', 'Start-MicrosoftTeamsChatJobByPlan', 
               'Find-GoogleDriveJobsByPlan', 'Get-GmailPolicy', 'Remove-BoxPlan', 
               'Get-PlanGroup', 'Add-SPConnection', 
               'Get-MicrosoftTeamsChatConnection', 'Remove-PSTFileJob', 
               'Add-GoogleChatPreMigration', 'Remove-PublicFolderJob', 'Get-SPPlan', 
               'Get-Mapping', 'Get-SlackJob', 'Start-MappingJob', 'Add-FSPlan', 
               'Remove-SPPlan', 'Add-SlackPlan', 'Remove-SlackDirectJob', 
               'Update-SlackPlan', 'Update-IMAPPOP3Plan', 'Get-ExchangeConnection', 
               'Get-ExchangeJob', 'Get-OneDrivePolicy', 'Add-GmailPreMigration', 
               'Remove-DropboxJob', 'Get-MicrosoftTeamsJob', 
               'Restart-MicrosoftTeamsJob', 'Add-GoogleDrivePreMigration', 
               'Start-Office365GroupJobByPlan', 'Add-BoxPreMigration', 
               'Get-AppProfile', 'Add-ExchangePlan', 'Get-MicrosoftTeamsConnection', 
               'Add-MicrosoftTeamsPlan', 'Get-FSJob', 'Get-SlackPolicy', 
               'Restart-SPJob', 'Add-PublicFolderPreMigration', 'Get-PlanGroupById', 
               'Add-UserMapping', 'Get-MicrosoftTeamsChatPlan', 'Update-DropboxPlan', 
               'Stop-SlackDirectJob', 'Get-Office365GroupConnection', 'Get-GmailJob', 
               'Restart-Office365GroupJob', 'Restart-DropboxJob', 'Get-OneDriveJob', 
               'Get-GmailConnection', 'Get-SPConnection', 'Add-GoogleChatPlan', 
               'Find-GmailJobsByPlan', 'Restart-IMAPPOP3Job', 
               'Update-SlackDirectPlan', 'Restart-PublicFolder', 
               'Find-MicrosoftTeamsJobsByPlan', 'Add-SPPlan', 'Get-BoxPlan', 
               'Update-ExchangePlan', 'Get-MicrosoftTeamsChatPolicy', 
               'Find-SlackJobsByPlan', 'Add-GmailPlan', 
               'Remove-MicrosoftTeamsChatJob', 'Update-MicrosoftTeamsPlan', 
               'Start-BoxJobByPlan', 'Update-PSTFilePlan', 'Update-SPConnection', 
               'Get-SlackPlan', 'Stop-GmailJob', 'Get-FSConnection', 
               'Add-OneDriveConnection', 'Add-PlanGroup', 
               'Search-ExchangeServiceProvider', 'Get-ExchangePolicy', 
               'Restart-SlackJob', 'Start-JobsByPlanGroup', 'Remove-FSPlan', 
               'Stop-MicrosoftTeamsChatJob', 'Get-SlackDirectPlan', 
               'Add-Office365GroupPlan', 'Add-TeamsChatPreMigration', 
               'Get-PSTFileJob', 'Get-FSPlan', 'Add-PSTFilePlan', 
               'Stop-MicrosoftTeamsJob', 'Get-GoogleChatPolicy', 
               'Add-PublicFolderPlan', 'Update-FSPlan', 'Stop-ExchangeJob', 
               'Find-IMAPPOP3JobsByPlan', 'Find-OneDriveJobsByPlan', 
               'Remove-GmailPlan', 'Stop-SlackJob', 'Get-PublicFolderPlan', 
               'Add-ConnectionSite', 'Get-Office365GroupJobs', 'Update-BoxPlan', 
               'Restart-GmailJob', 'Remove-BoxJob', 'Get-MicrosoftTeamsChatJob', 
               'Get-OneDrivePlan', 'Update-GoogleChatPlan', 'Get-OneDriveConnection', 
               'Add-ExchangePreMigration', 'Remove-DropboxPlan', 'Stop-PlanGroup', 
               'Remove-OneDrivePlan', 'Remove-FSJob', 'Get-IMAPPOP3Policy', 
               'Get-BoxPolicy', 'Add-BoxPlan', 'Restart-GoogleDriveJob', 
               'Update-MicrosoftTeamsChatPlan', 'Restart-SlackDirectJob', 
               'Remove-PlanGroup', 'Start-MicrosoftTeamsJobByPlan', 
               'Find-FSJobsByPlan', 'Remove-IMAPPOP3Plan', 
               'Complete-MicrosoftSlackPlan', 'Remove-PublicFolderPlan', 
               'Stop-BoxJob', 'Add-TeamsPreMigration', 'Down-PreMigrationReportLoad', 
               'Add-OneDrivePreMigration', 'Add-DropboxPlan', 'Get-GoogleDrivePlan', 
               'Get-GoogleDrivePolicy', 'Remove-ExchangeJob', 
               'Remove-Office365GroupPlan', 'Restart-OneDriveJob', 
               'Remove-IMAPPOP3Job', 'Start-PreMigration', 'Stop-GoogleDriveJob', 
               'Restart-ExchangeJob', 'Stop-PublicFolderJob', 'Get-SPJob', 
               'Add-OneDrivePlan', 'Get-Database', 'Get-IMAPPOP3Plan', 
               'Update-Office365GroupPlan', 'Add-DropboxPreMigration', 
               'Remove-MicrosoftTeamsChatPlan', 'Get-GmailPlan', 
               'Update-GoogleGroupPlan', 'Get-SPPolicy', 'New-DatabaseObject', 
               'New-PSTFileMappingContentObject', 'New-SlackMappingContentObject', 
               'New-IMAPPOP3PlanSettingsObject', 'New-BoxObject', 
               'New-DropBoxPreMigrationObject', 'New-FileSystemAdvancedObject', 
               'New-GmailMappingContentObject', 
               'New-Office365GroupJobExecutionObject', 
               'New-PublicFolderConnectionObject', 'New-SharePointUpdateObject', 
               'New-GoogleChatJobExecutionObject', 
               'New-DropBoxAdvancedSettingsObject', 
               'New-OneDriveConnectionOnlineObject', 
               'New-GoogleDriveJobExecutionObject', 
               'New-DropboxPlanSettingsObject', 'New-OneDrivePlanSettingsObject', 
               'New-OneDriveConnectionCollectionObject', 
               'New-GoogleChatPreMappingObject', 'New-IMAPPOP3PlanObject', 
               'New-PSTFilePlanSettingObject', 
               'New-GoogleDriveMappingContentObject', 
               'New-GoogleGroupMigrationExchangeMailboxObject', 
               'New-UpdateOffice365GroupPlanObject', 
               'New-GmailMigrationExchangeMailboxObject', 
               'New-TeamsChatPreMigrationObject', 'New-TeamsPreMigrationObject', 
               'New-OneDriveObject', 'New-UpdateMappingOptionsObject', 
               'New-GoogleChatPlanObject', 'New-UpdatePublicFoldersPlanObject', 
               'New-ExchangeDistributionGroupPlanObject', 
               'New-UpdateMSTeamsPlanObject', 'New-SharePointPlanSettingsObject', 
               'New-BoxJobExecutionObject', 'New-IMAPPOP3MailBoxObject', 
               'New-BoxAdvancedSettingsObject', 
               'New-SharePointPlanExecutionObject', 
               'New-OneDriveJobExecutionObject', 'New-FSMigrationSharePointObject', 
               'New-MSTeamsChatPlanObject', 'New-DropboxPlanObject', 
               'New-SlackDirectMappingObject', 'New-MSTeamsJobExecutionObject', 
               'New-SlackDirectPlanSettingsObject', 
               'New-ConversationsMigrationSettingsObject', 
               'New-GmailPlanSettingsObject', 'New-SharePointConnectionSiteObject', 
               'New-IMAPPOP3MappingObject', 'New-UserMappingsObject', 
               'New-ExchangeServerOptionObject', 'New-UpdateExchangePlanObject', 
               'New-DistributionGroupDestinationMappingObject', 
               'New-ExchangeConnectionObject', 'New-UpdateGmailPlanObject', 
               'New-ScheduleObject', 'New-MSTeamsObject', 'New-SlackCompleteObject', 
               'New-ExchangePreMappingObject', 'New-PSTFileMappingObject', 
               'New-MSTeamsMappingObject', 'New-IMAPPOP3JobExecutionObject', 
               'New-SlackDirectPreMigrationObject', 'New-BoxMappingContentObject', 
               'New-SharePointPreMappingObject', 
               'New-SharePointPreMigrationObject', 'New-BoxPlanMappingObject', 
               'New-GoogleGroupMappingContentObject', 
               'New-UpdateDropBoxPlanObject', 'New-BoxPreMigrationObject', 
               'New-SlackDirectPlanObject', 'New-Office365GroupMappingObject', 
               'New-ExchangeMappingContentObject', 'New-FSJobExecutionObject', 
               'New-BoxPlanSettingsObject', 'New-BoxMigrationSharePointObject', 
               'New-MSTeamsChatPlanSettingsObject', 'New-SlackJobExecutionObject', 
               'New-Office365GroupPlanObject', 'New-DropboxPlanMappingObject', 
               'New-PstPlanExecutionObject', 
               'New-ExchangeDistributionGroupPlanSettingsObject', 
               'New-DropboxMappingContentObject', 
               'New-ImapMigrationExchangeMailboxObject', 
               'New-SimpleScheduleObject', 'New-TeamsPreMappingObject', 
               'New-SlackPreMappingObject', 
               'New-Office365GroupPlanExecutionObject', 
               'New-GoogleDriveMigrationSharePointObject', 'New-SharePointObject', 
               'New-MSTeamsChatPlanExecutionObject', 
               'New-UpdateSlackDirectPlanObject', 'New-DropboxObject', 
               'New-GroupsPreMappingObject', 'New-SharePointJobExecutionObject', 
               'New-OneDriveMappingObject', 'New-PSTFileObject', 
               'New-UpdateGoogleChatPlanObject', 
               'New-UpdateDistributionGroupPlanObject', 'New-FSPreMigrationObject', 
               'New-PublicFolderJobExecutionObject', 'New-GoogleDriveObject', 
               'New-FSMappingContentObject', 'New-GoogleDrivePreMigrationObject', 
               'New-SharePointPlanObject', 'New-SharePointConnectionOnlineObject', 
               'New-PlanGroupObject', 'New-SlackDirectJobExecutionObject', 
               'New-SlackPreMigrationObject', 'New-GmailPlanObject', 
               'New-GmailPreMappingObject', 'New-MSTeamsChatMappingObject', 
               'New-SharePointMappingObject', 
               'New-DistributionGroupSourceMappingObject', 'New-FSMappingObject', 
               'New-GoogleDriveMappingObject', 'New-FileSystemPreMappingObject', 
               'New-ExchangeOnlineConnectionOptionObject', 
               'New-SlackDirectPreMappingObject', 'New-GoogleDrivePlanObject', 
               'New-GmailJobExecutionObject', 'New-PFPreMappingObject', 
               'New-MappingJobExecutionObject', 'New-OneDrivePlanObject', 
               'New-TeamsCompleteObject', 'New-ExchangeJobExecutionObject', 
               'New-UpdateIMAPPOP3PlanObject', 'New-UpdateGoogleDrivePlanObject', 
               'New-MSTeamsMappingContentObject', 'New-TeamsChatPreMappingObject', 
               'New-Office365GroupObject', 'New-PublicFolderObject', 
               'New-UpdateSharePointConnectionCollectionObject', 
               'New-GoogleChatPreMigrationObject', 
               'New-GoogleDriveAdvancedSettingsObject', 
               'New-OneDriveMappingContentObject', 'New-FSPathObject', 
               'New-SharePointMappingContentObject', 'New-FSPlanObject', 
               'New-PublicFolderMappingContentObject', 'New-PSTFilePlanObject', 
               'New-Office365GroupMappingContentObject', 
               'New-ExchangePlanSettingsObject', 'New-PublicFoldersSettingsObject', 
               'New-MSTeamsPlanSettingsObject', 'New-PlanExecutionObject', 
               'New-PlanNameLabelObject', 'New-GoogleGroupPlanObject', 
               'New-PublicFolderMappingObject', 'New-UpdateMSTeamsChatPlanObject', 
               'New-UpdateFSPlanObject', 'New-ExchangePreMigrationObject', 
               'New-UpdatePSTFilePlanObject', 
               'New-PublicFolderConnectionOptionObject', 
               'New-GoogleChatMappingObject', 
               'New-MSTeamsChatMappingContentObject', 'New-UpdateBoxPlanObject', 
               'New-FSPlanSettingsObject', 'New-DropboxMigrationSharePointObject', 
               'New-ChannelMappingObject', 'New-MSTeamsPlanObject', 
               'New-DbServiceAccountObject', 
               'New-ExchangeDistributionGroupMappingObject', 
               'New-CredentialObject', 'New-GmailMappingObject', 
               'New-SlackPlanObject', 'New-GoogleGroupMappingObject', 
               'New-SharePointConnectionOnPremisesObject', 
               'New-UpdateGoogleGroupPlanSettingsObject', 
               'New-GmailPreMigrationObject', 'New-SlackMappingObject', 
               'New-GroupsPreMigrationObject', 'New-MappingDetailObject', 
               'New-BasicCredentialObject', 'New-IMAPPOP3ConnectionObject', 
               'New-PublicFolderPlanObject', 
               'New-Office365GroupPlanSettingsObject', 
               'New-SharePointConnectionCollectionObject', 
               'New-DropboxJobExecutionObject', 
               'New-UpdateOneDriveConnectionCollectionObject', 
               'New-PostMigrationOptionsObject', 'New-MultigeoTenantObject', 
               'New-GoogleGroupPlanSettingsObject', 'New-UpdateSlackPlanObject', 
               'New-SlackPlanSettingsObject', 'New-ExchangeMappingObject', 
               'New-OneDrivePreMigrationObject', 'New-PFPreMigrationObject', 
               'New-GoogleChatPlanSettingsObject', 
               'New-PSTFileConnectionOptionObject', 
               'New-GoogleDrivePlanSettingsObject', 'New-ExchangePlanObject', 
               'New-OneDrivePreMappingObject', 'New-PSTFileJobExecutionObject', 
               'New-SlackDirectMappingContentObject', 
               'New-PlanGroupExecutionObject', 
               'New-GoogleChatMappingContentObject', 'New-BoxPlanObject', 
               'New-IMAPPOP3MappingContentObject', 
               'New-OneDrivePlanExecutionObject', 
               'New-ExchangeOnPremisesConnectionOptionObject', 
               'New-ExchangePlanExecutionObject', 'New-OneDriveUpdateObject', 
               'New-ExchangeDistributionGroupMappingContentObject', 
               'New-PublicFolderPlanExecutionObject', 
               'New-MSTeamsChatJobExecutionObject', 'New-ExchangeMailboxObject', 
               'New-MappingsObject', 'New-MSTeamsPlanExecutionObject', 
               'New-SlackMigrationMSTeamsObject'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


