<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER DestinationCredential
    {AvePoint.Migration.Api.Models.AccountModel}

.PARAMETER SourceConnectionId
    

.PARAMETER Contents
    

#>
function New-FSMappingObject
{
    param(    
        [Parameter(Mandatory = $true)]
        [AvePoint.PowerShell.FLYMigration.Models.SharePointCredential]
        $DestinationCredential,
    
        [Parameter(Mandatory = $true)]
        [string]
        $SourceConnectionId,
    
        [Parameter(Mandatory = $true)]
        [AvePoint.PowerShell.FLYMigration.Models.FSMappingContent[]]
        $Contents
    )
    
    $Object = New-Object -TypeName AvePoint.PowerShell.FLYMigration.Models.FSMappingModel

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
