<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER BusinessUnit
    

.PARAMETER Name
    

.PARAMETER Wave
    

#>
function New-PlanNameLabelObject
{
    param(    
        [Parameter(Mandatory = $true)]
        [string]
        $BusinessUnit,
    
        [Parameter(Mandatory = $true)]
        [string]
        $Name,
    
        [Parameter(Mandatory = $true)]
        [string]
        $Wave
    )
    
    $Object = New-Object -TypeName AvePoint.PowerShell.FLYMigration.Models.PlanNameLabel

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
