<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER AppProfileName
    the name of app profile.

.PARAMETER AccountName
    the name of service account.

#>
function New-SharePointCredentialObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [string]
        $AppProfileName,
    
        [Parameter(Mandatory = $false)]
        [string]
        $AccountName
    )
    
    $Object = New-Object -TypeName AvePoint.PowerShell.FLYMigration.Models.SharePointCredential

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
