<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    Account Model,

.DESCRIPTION
    Account Model,

.PARAMETER Username
    Account name

.PARAMETER Password
    Password of the account

.PARAMETER AppProfile
    Name of the app profile to connect to O365

#>
function New-AccountObject
{
    param(    
        [Parameter(Mandatory = $true)]
        [string]
        $Username,
    
        [Parameter(Mandatory = $true)]
        [string]
        $Password,
    
        [Parameter(Mandatory = $false)]
        [string]
        $AppProfile
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.FLYMigration.v001.Models.AccountModel

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
