<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER Contents
    

.PARAMETER DestinationAccount
    {AvePoint.Migration.Api.Models.AccountModel}

.PARAMETER SourceAccount
    {AvePoint.Migration.Api.Models.AccountModel}

#>
function New-SharePointMappingObject
{
    param(    
        [Parameter(Mandatory = $true)]
        [Microsoft.PowerShell.FLYMigration.v001.Models.SharePointMappingContent[]]
        $Contents,
    
        [Parameter(Mandatory = $true)]
        [Microsoft.PowerShell.FLYMigration.v001.Models.AccountModel]
        $DestinationAccount,
    
        [Parameter(Mandatory = $true)]
        [Microsoft.PowerShell.FLYMigration.v001.Models.AccountModel]
        $SourceAccount
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.FLYMigration.v001.Models.SharePointMappingModel

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
