<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>


# If the user supplied -Prefix to Import-Module, that applies to the nested module as well
# Force import the nested module again without -Prefix

function Covert-UtcTime($Time)
{
	$Result = @{ HasError = $false ; Message = "";Time = ""}
	$Pattern = "^[1-9][0-9]{3}\-([0-9][1-9]|[1-9][0-9])\-([0-9][1-9]|[1-9][0-9]) [0-9]{2}\:[0-9]{2}\:[0-9]{2}"
	$MathResult = $Time -match $Pattern
	if($MathResult)
	{
		$TimeZone = "+"+(Get-TimeZone).BaseUtcOffset.toString().Substring(0,5)
		$SetTime = ([Datetime]$Time).ToString("o")+$TimeZone
		$Result["Time"] = $SetTime;
		if(([Datetime]$Time.Replace('"',"")) -gt [Datetime]::Now)
		{
			$Result["HasError"] = $true;
			$Result["Message"] = "The time configured cannot be later than the current time."
			return $Result
		}
		return $Result;
	}
	else
	{
		$Result["HasError"] = $true;
		$Result["Message"] = "Please check if the time format you entered is correct."
		return $Result;
	}
}

