<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER Contents
    

.PARAMETER Source
    

.PARAMETER DestinationConnectionId
    

#>
function New-IMAPPOP3MappingObject
{
    param(    
        [Parameter(Mandatory = $true)]
        [AvePoint.PowerShell.FLYMigration.Models.IMAPPOP3MappingContentModel[]]
        $Contents,
    
        [Parameter(Mandatory = $true)]
        [AvePoint.PowerShell.FLYMigration.Models.IMAPPOP3ConnectionModel]
        $Source,
    
        [Parameter(Mandatory = $true)]
        [string]
        $DestinationConnectionId
    )
    
    $Object = New-Object -TypeName AvePoint.PowerShell.FLYMigration.Models.IMAPPOP3MappingModel

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
