<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER DestinationCredential
    {AvePoint.Migration.Api.Models.SharePointCredential}

.PARAMETER SourceCredential
    {AvePoint.Migration.Api.Models.SharePointCredential}

.PARAMETER Contents
    

#>
function New-SharePointMappingObject
{
    param(    
        [Parameter(Mandatory = $true)]
        [AvePoint.PowerShell.FLYMigration.Models.SharePointCredential]
        $DestinationCredential,
    
        [Parameter(Mandatory = $true)]
        [AvePoint.PowerShell.FLYMigration.Models.SharePointCredential]
        $SourceCredential,
    
        [Parameter(Mandatory = $true)]
        [AvePoint.PowerShell.FLYMigration.Models.SharePointMappingContent[]]
        $Contents
    )
    
    $Object = New-Object -TypeName AvePoint.PowerShell.FLYMigration.Models.SharePointMappingModel

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
