// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AvePoint.PowerShell.FLYMigration.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class JobSummaryModel
    {
        /// <summary>
        /// Initializes a new instance of the JobSummaryModel class.
        /// </summary>
        public JobSummaryModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JobSummaryModel class.
        /// </summary>
        /// <param name="id">Id of the job</param>
        /// <param name="startTime">Start time of the job</param>
        /// <param name="finishTime">Finish Time of the job</param>
        /// <param name="planName">The name of the migration plan</param>
        /// <param name="progress">The progress of the job</param>
        /// <param name="status">The Status of the job
        /// Running, Waiting, Finished, Failed, Stopped,
        /// FinishedWithException</param>
        public JobSummaryModel(string id = default(string), System.DateTime? startTime = default(System.DateTime?), System.DateTime? finishTime = default(System.DateTime?), string planName = default(string), double? progress = default(double?), string status = default(string))
        {
            Id = id;
            StartTime = startTime;
            FinishTime = finishTime;
            PlanName = planName;
            Progress = progress;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets id of the job
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets start time of the job
        /// </summary>
        [JsonProperty(PropertyName = "startTime")]
        public System.DateTime? StartTime { get; set; }

        /// <summary>
        /// Gets or sets finish Time of the job
        /// </summary>
        [JsonProperty(PropertyName = "finishTime")]
        public System.DateTime? FinishTime { get; set; }

        /// <summary>
        /// Gets or sets the name of the migration plan
        /// </summary>
        [JsonProperty(PropertyName = "planName")]
        public string PlanName { get; set; }

        /// <summary>
        /// Gets or sets the progress of the job
        /// </summary>
        [JsonProperty(PropertyName = "progress")]
        public double? Progress { get; set; }

        /// <summary>
        /// Gets or sets the Status of the job
        /// Running, Waiting, Finished, Failed, Stopped, FinishedWithException
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
