// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AvePoint.PowerShell.FLYMigration
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SPConnection.
    /// </summary>
    public static partial class SPConnectionExtensions
    {
            /// <summary>
            /// Add a migration connection
            /// </summary>
            /// <remarks>
            /// Returns a list of registration result
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static ServiceResponseListSharePointConnectionRegistrationResultModel Add(this ISPConnection operations, SharePointConnectionCollectionModel model)
            {
                return operations.AddAsync(model).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add a migration connection
            /// </summary>
            /// <remarks>
            /// Returns a list of registration result
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ServiceResponseListSharePointConnectionRegistrationResultModel> AddAsync(this ISPConnection operations, SharePointConnectionCollectionModel model, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.AddWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
