<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER SynchronizeDeletion
    whether to delete the destination migrated e-mails that have been deleted from the source

.PARAMETER PolicyId
    the id of migration policy

.PARAMETER MigrateDistributionGroups
    whether to migrate distribution groups in the source mailbox

.PARAMETER Schedule
    the schedule for the migration

.PARAMETER MigrateMailboxPermissions
    whether to migrate permissions of the source mailbox

.PARAMETER MigrateAutoCompleteList
    whether to migrate Auto-Complete List,
The Auto-Complete List is a list of names and email addresses that can be suggested when the mailbox user configures users in the To, Cc, and Bcc lines. 
The suggestions are from the email messages that the mailbox user have sent before

.PARAMETER MigrateContacts
    whether to migrate contacts in the source mailbox

.PARAMETER MigrateMailboxRules
    whether to migrate source mailbox rules

.PARAMETER MigratePublicFolders
    whether to migrate public folders in the source mailbox

.PARAMETER DatabaseId
    the id of migration database

.PARAMETER PlanGroups
    

.PARAMETER NameLabel
    Large migration projects are often phased over several waves, each containing multiple plans. 
To easily generate migration reports for each project or wave, we recommend the Example name format Business Unit_Wave_Plan

#>
function New-ExchangePlanSettingsObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [switch]
        $SynchronizeDeletion,
    
        [Parameter(Mandatory = $false)]
        [string]
        $PolicyId,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $MigrateDistributionGroups,
    
        [Parameter(Mandatory = $false)]
        [AvePoint.PowerShell.FLYMigration.Models.SimpleSchedule]
        $Schedule,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $MigrateMailboxPermissions,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $MigrateAutoCompleteList,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $MigrateContacts,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $MigrateMailboxRules,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $MigratePublicFolders,
    
        [Parameter(Mandatory = $false)]
        [string]
        $DatabaseId,
    
        [Parameter(Mandatory = $false)]
        [string[]]
        $PlanGroups,
    
        [Parameter(Mandatory = $true)]
        [AvePoint.PowerShell.FLYMigration.Models.PlanNameLabel]
        $NameLabel
    )
    
    $Object = New-Object -TypeName AvePoint.PowerShell.FLYMigration.Models.ExchangePlanSettingsModel

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
