<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER SiteCollections
    

.PARAMETER Account
    

.PARAMETER AppProfileName
    

.PARAMETER Password
    

#>
function New-SharePointConnectionObject
{
    param(    
        [Parameter(Mandatory = $true)]
        [string[]]
        $SiteCollections,
    
        [Parameter(Mandatory = $false)]
        [string]
        $Account,
    
        [Parameter(Mandatory = $false)]
        [string]
        $AppProfileName,
    
        [Parameter(Mandatory = $false)]
        [string]
        $Password
    )
    
    $Object = New-Object -TypeName AvePoint.PowerShell.FLYMigration.Models.SharePointConnectionModel

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
