// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AvePoint.Migration.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AppProfileModel
    {
        /// <summary>
        /// Initializes a new instance of the AppProfileModel class.
        /// </summary>
        public AppProfileModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppProfileModel class.
        /// </summary>
        /// <param name="id">Id of the App Profile</param>
        /// <param name="name">Name of the App Profile</param>
        /// <param name="globalAdministrator">Name of Office 365 Global
        /// Administrator</param>
        /// <param name="status">Status of the App Profile, Possible values
        /// includes: ['Active', 'Inactive', 'Draft']</param>
        public AppProfileModel(string id = default(string), string name = default(string), string globalAdministrator = default(string), string status = default(string))
        {
            Id = id;
            Name = name;
            GlobalAdministrator = globalAdministrator;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets id of the App Profile
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets name of the App Profile
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets name of Office 365 Global Administrator
        /// </summary>
        [JsonProperty(PropertyName = "globalAdministrator")]
        public string GlobalAdministrator { get; set; }

        /// <summary>
        /// Gets or sets status of the App Profile, Possible values includes:
        /// ['Active', 'Inactive', 'Draft']
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
