// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AvePoint.PowerShell.FLYMigration.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExchangeMappingContentModel
    {
        /// <summary>
        /// Initializes a new instance of the ExchangeMappingContentModel
        /// class.
        /// </summary>
        public ExchangeMappingContentModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExchangeMappingContentModel
        /// class.
        /// </summary>
        /// <param name="convertToSharedMailbox">whether to convert the
        /// destination mailbox to the shared mailbox</param>
        /// <param name="migrateArchivedMailboxOrFolder">whether to migrate the
        /// archived mailbox/folder</param>
        /// <param name="migrateRecoverableItemsFolder">whether to migrate
        /// recoverable items folder</param>
        public ExchangeMappingContentModel(ExchangeMailboxModel source, ExchangeMailboxModel destination, bool? convertToSharedMailbox = default(bool?), bool? migrateArchivedMailboxOrFolder = default(bool?), bool? migrateRecoverableItemsFolder = default(bool?))
        {
            Source = source;
            Destination = destination;
            ConvertToSharedMailbox = convertToSharedMailbox;
            MigrateArchivedMailboxOrFolder = migrateArchivedMailboxOrFolder;
            MigrateRecoverableItemsFolder = migrateRecoverableItemsFolder;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public ExchangeMailboxModel Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "destination")]
        public ExchangeMailboxModel Destination { get; set; }

        /// <summary>
        /// Gets or sets whether to convert the destination mailbox to the
        /// shared mailbox
        /// </summary>
        [JsonProperty(PropertyName = "convertToSharedMailbox")]
        public bool? ConvertToSharedMailbox { get; set; }

        /// <summary>
        /// Gets or sets whether to migrate the archived mailbox/folder
        /// </summary>
        [JsonProperty(PropertyName = "migrateArchivedMailboxOrFolder")]
        public bool? MigrateArchivedMailboxOrFolder { get; set; }

        /// <summary>
        /// Gets or sets whether to migrate recoverable items folder
        /// </summary>
        [JsonProperty(PropertyName = "migrateRecoverableItemsFolder")]
        public bool? MigrateRecoverableItemsFolder { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Source == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Source");
            }
            if (Destination == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Destination");
            }
            if (Source != null)
            {
                Source.Validate();
            }
            if (Destination != null)
            {
                Destination.Validate();
            }
        }
    }
}
