// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AvePoint.PowerShell.FLYMigration.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SharePointMappingModel
    {
        /// <summary>
        /// Initializes a new instance of the SharePointMappingModel class.
        /// </summary>
        public SharePointMappingModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SharePointMappingModel class.
        /// </summary>
        /// <param
        /// name="sourceCredential">{AvePoint.Migration.Api.Models.SharePointCredential}</param>
        /// <param
        /// name="destinationCredential">{AvePoint.Migration.Api.Models.SharePointCredential}</param>
        public SharePointMappingModel(SharePointCredential sourceCredential, SharePointCredential destinationCredential, IList<SharePointMappingContent> contents)
        {
            SourceCredential = sourceCredential;
            DestinationCredential = destinationCredential;
            Contents = contents;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets {AvePoint.Migration.Api.Models.SharePointCredential}
        /// </summary>
        [JsonProperty(PropertyName = "sourceCredential")]
        public SharePointCredential SourceCredential { get; set; }

        /// <summary>
        /// Gets or sets {AvePoint.Migration.Api.Models.SharePointCredential}
        /// </summary>
        [JsonProperty(PropertyName = "destinationCredential")]
        public SharePointCredential DestinationCredential { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contents")]
        public IList<SharePointMappingContent> Contents { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SourceCredential == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SourceCredential");
            }
            if (DestinationCredential == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DestinationCredential");
            }
            if (Contents == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Contents");
            }
            if (Contents != null)
            {
                foreach (var element in Contents)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
