// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AvePoint.PowerShell.FLYMigration.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExchangePlanExecutionModel
    {
        /// <summary>
        /// Initializes a new instance of the ExchangePlanExecutionModel class.
        /// </summary>
        public ExchangePlanExecutionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExchangePlanExecutionModel class.
        /// </summary>
        /// <param name="migrationType">Possible values include: 'Incremental',
        /// 'Full', 'EnableForward', 'ForwardAndCopy',
        /// 'DisableForwarding'</param>
        public ExchangePlanExecutionModel(string migrationType)
        {
            MigrationType = migrationType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Incremental', 'Full',
        /// 'EnableForward', 'ForwardAndCopy', 'DisableForwarding'
        /// </summary>
        [JsonProperty(PropertyName = "migrationType")]
        public string MigrationType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (MigrationType == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MigrationType");
            }
        }
    }
}
