// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AvePoint.PowerShell.FLYMigration.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PSTFileMappingModel
    {
        /// <summary>
        /// Initializes a new instance of the PSTFileMappingModel class.
        /// </summary>
        public PSTFileMappingModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PSTFileMappingModel class.
        /// </summary>
        public PSTFileMappingModel(PSTFileConnectionOption pstFileConnection, ExchangeOnlineConnectionOption exchangeConnectionOption, IList<PSTFileMappingContentModel> contents)
        {
            PstFileConnection = pstFileConnection;
            ExchangeConnectionOption = exchangeConnectionOption;
            Contents = contents;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pstFileConnection")]
        public PSTFileConnectionOption PstFileConnection { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exchangeConnectionOption")]
        public ExchangeOnlineConnectionOption ExchangeConnectionOption { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contents")]
        public IList<PSTFileMappingContentModel> Contents { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (PstFileConnection == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PstFileConnection");
            }
            if (ExchangeConnectionOption == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ExchangeConnectionOption");
            }
            if (Contents == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Contents");
            }
            if (PstFileConnection != null)
            {
                PstFileConnection.Validate();
            }
            if (ExchangeConnectionOption != null)
            {
                ExchangeConnectionOption.Validate();
            }
            if (Contents != null)
            {
                foreach (var element in Contents)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
