// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AvePoint.PowerShell.FLYMigration.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PSTFileConnectionAdvancedSettingsOption
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PSTFileConnectionAdvancedSettingsOption class.
        /// </summary>
        public PSTFileConnectionAdvancedSettingsOption()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PSTFileConnectionAdvancedSettingsOption class.
        /// </summary>
        /// <param name="agentHostName">This setting allows you to specify an
        /// Agent to establish connections and run migrations when there are
        /// more than one Agent.
        /// If this setting is not configured, our solution will select an
        /// Agent at random.</param>
        public PSTFileConnectionAdvancedSettingsOption(string agentHostName = default(string))
        {
            AgentHostName = agentHostName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets this setting allows you to specify an Agent to
        /// establish connections and run migrations when there are more than
        /// one Agent.
        /// If this setting is not configured, our solution will select an
        /// Agent at random.
        /// </summary>
        [JsonProperty(PropertyName = "agentHostName")]
        public string AgentHostName { get; set; }

    }
}
