// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AvePoint.PowerShell.FLYMigration.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SharePointConnectionCollectionModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SharePointConnectionCollectionModel class.
        /// </summary>
        public SharePointConnectionCollectionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SharePointConnectionCollectionModel class.
        /// </summary>
        public SharePointConnectionCollectionModel(IList<SharePointConnectionModel> connections)
        {
            Connections = connections;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "connections")]
        public IList<SharePointConnectionModel> Connections { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Connections == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Connections");
            }
            if (Connections != null)
            {
                foreach (var element in Connections)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
